// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MarkDownEditor.XamarinIOS
{
	public partial class HTMLViewController : UIView
	{
		public HTMLViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
